package buildstep

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
)

// dockerbuild.go turns a built Next.js (App Router, standalone) demo into an
// opaque production Docker image and pushes it to a registry. Only the compiled
// standalone output ships in the image — no .tsx/source — so a customer can run
// the demo on their own LAN without seeing our code. CRN writes its own known-
// good Dockerfile (deterministic, mirrors the fitt-build harness asset) rather
// than trusting whatever the model produced, then execs the host `docker`.

// productionDockerfile is the multi-stage build for a Next.js app using
// output:"standalone". The runner stage copies ONLY .next/standalone + static +
// public, so source files never land in the image. Kept in sync with the
// fitt-build skill's assets/Dockerfile.
const productionDockerfile = `# Auto-written by FITT Code Runner — production image for this demo.
# Multi-stage build for a Next.js (App Router) app using output: "standalone".
# The runner copies ONLY the compiled standalone output — no source ships.
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci --ignore-scripts

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# prisma generate needs no database; safe no-op if the project has no Prisma.
RUN npx prisma generate 2>/dev/null || true
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
CMD ["node", "server.js"]
`

const dockerIgnore = `node_modules
.next
.git
.env
.env.*
Dockerfile
.dockerignore
npm-debug.log
`

// migrateDockerfile packages ONLY the DB layer (prisma CLI + schema + seed) —
// no app source. On the customer's machine it runs `prisma db push` (sync schema)
// then `prisma db seed` and exits.
//
// Why db push, not migrate deploy: the harness regenerates a single squashed
// schema every build (no committed migration history). migrate deploy would need
// a baked `0_init` migration whose content changes across versions but keeps the
// same name — so upgrading the demo to a new image version checksum-FAILS ("migration
// modified after applied") even for purely additive schema changes, and the demo
// won't start. db push has no migration history/checksum: it diffs the LIVE DB
// against the schema each run, applying additive deltas cleanly. It is NOT given
// --accept-data-loss, so a destructive change (dropped column/table) errors loudly
// for the operator to handle rather than silently dropping customer data. The seed
// uses upsert keyed by a stable id, so re-running on every start is safe.
const migrateDockerfile = `# Auto-written by FITT Code Runner — DB migrate+seed for this demo.
# Runs once against the customer's Postgres (migrate-on-start), then exits.
# Contains only the DB layer (prisma) — no app source ships.
FROM node:20-alpine
RUN apk add --no-cache libc6-compat openssl
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci --ignore-scripts
COPY prisma ./prisma
RUN npx prisma generate
# db push syncs the schema to the live DB (no migration history/checksum) so version
# upgrades apply additive deltas cleanly; --skip-generate reuses the client baked above.
CMD ["sh", "-c", "npx prisma db push --skip-generate && npx prisma db seed"]
`

// customerCompose is the self-contained runner the customer gets: Postgres (data
// in a named volume) + a one-shot migrate service (schema+seed) + the opaque app
// image. app waits for migrate to finish. Placeholders are rendered per build.
const customerCompose = `# Auto-generated by FITT Code Runner — run this demo on your own machine/LAN.
#   docker compose -f docker-compose.customer.yml up -d
# No source ships (app is a compiled image); your data stays in the dbdata volume.
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - dbdata:/var/lib/postgresql/data

  migrate:
    image: {{MIGRATE_IMAGE}}
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://app:app@db:5432/app?schema=public"
    restart: "no"

  app:
    image: {{APP_IMAGE}}
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: "postgresql://app:app@db:5432/app?schema=public"
    ports:
      - "${APP_PORT:-{{PORT}}}:3000"

volumes:
  dbdata:
`

// DemoEnvExample is the runtime env contract for the delivered demo image — an
// example a consumer (FTC DV) can adapt. The operator supplies the real values at
// run time (compose/orchestrator); NONE of these are baked into the image. Mirrors
// what customerCompose injects, so keep the two in step.
type DemoEnvExample struct {
	// DatabaseURL is REQUIRED — both the app and the migrate image read it.
	DatabaseURL string `json:"DATABASE_URL"`
	// Port is the port the app listens on INSIDE the container (fixed).
	Port string `json:"PORT"`
	// AppPort is the suggested HOST port to publish → container 3000 (per-project,
	// avoids collisions); override freely.
	AppPort string `json:"APP_PORT"`
}

// NewDemoEnvExample builds the env contract for a demo whose per-project host port
// is `port` (from ScaffoldPort).
func NewDemoEnvExample(port int) DemoEnvExample {
	return DemoEnvExample{
		DatabaseURL: "postgresql://USER:PASSWORD@HOST:5432/DB?schema=public",
		Port:        "3000",
		AppPort:     strconv.Itoa(port),
	}
}

const installMD = `# INSTALL — รัน demo นี้บนเครื่องคุณ

Bundle นี้รัน demo ทั้งหมดในเครื่อง/วงแลนของคุณเอง: **ไม่มี source code** (app เป็น image ที่ compile แล้ว), **data อยู่ใน Postgres volume ในเครื่องคุณ**.

## ต้องมี
- Docker + Docker Compose
- เข้าถึง image registry ได้ (หรือมีไฟล์ image tarball)

## รัน
` + "```bash" + `
# ถ้า registry ต้อง login (deploy token):
docker login {{REGISTRY}} -u <user> -p <token>

# start ทั้งหมด (Postgres + schema/seed + app):
docker compose -f docker-compose.customer.yml up -d
` + "```" + `
เปิด http://localhost:{{PORT}}

## เกิดอะไรขึ้น
1. ` + "`db`" + ` — Postgres start (data เก็บใน volume ` + "`dbdata`" + `)
2. ` + "`migrate`" + ` — สร้าง schema + seed data แล้ว exit (รันครั้งเดียว)
3. ` + "`app`" + ` — demo, start หลัง migrate เสร็จ

## อัปเดตเป็นเวอร์ชันใหม่
เปลี่ยน tag ` + "`:v<n>`" + ` ใน ` + "`docker-compose.customer.yml`" + ` แล้ว ` + "`up -d`" + ` ใหม่ — data ใน ` + "`dbdata`" + ` อยู่ครบ

## ⚠️ ห้าม
- ` + "`docker compose down -v`" + ` — ` + "`-v`" + ` ลบ volume = **ล้าง data ทิ้ง**
`

// MigrateImageTag is the companion migrate image's tag: the app tag with a
// "-migrate" suffix on the repo (e.g. ".../crn-demo-<slug>-<id8>-migrate:v<n>").
func MigrateImageTag(registry, name, projectID string, buildNo int) string {
	t := DemoImageTag(registry, name, projectID, buildNo)
	if i := strings.LastIndex(t, ":v"); i >= 0 {
		return t[:i] + "-migrate" + t[i:]
	}
	return t + "-migrate"
}

// DemoImageTag builds the image tag for a build:
// "<registry>/crn-demo-<slug>-<id8>:v<n>" (registry omitted when empty -> a
// local-only tag). The 8-char project-id suffix keeps two different projects
// that happen to share a demo name from colliding on the same image repo (both
// use per-project build numbers, so v1 would otherwise overwrite v1). name is
// sanitized to the docker repo charset.
func DemoImageTag(registry, name, projectID string, buildNo int) string {
	id8 := projectID
	if len(id8) > 8 {
		id8 = id8[:8]
	}
	repo := "crn-demo-" + dockerSlug(name)
	if id8 != "" {
		repo += "-" + id8
	}
	if registry != "" {
		repo = strings.TrimRight(registry, "/") + "/" + repo
	}
	return fmt.Sprintf("%s:v%d", repo, buildNo)
}

// dockerSlug lowercases name and keeps only the docker repo charset
// ([a-z0-9._-]), collapsing runs of other characters to a single "-". Falls back
// to "demo" if nothing usable remains.
func dockerSlug(name string) string {
	var b strings.Builder
	lastDash := false
	for _, r := range strings.ToLower(name) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
			lastDash = false
		default:
			if !lastDash && b.Len() > 0 {
				b.WriteByte('-')
				lastDash = true
			}
		}
	}
	s := strings.Trim(b.String(), "-")
	if s == "" {
		return "demo"
	}
	return s
}

// IsNextApp reports whether dir looks like a Next.js app (package.json depends on
// "next"). The docker-image pipeline only handles Next standalone builds; other
// stacks are skipped (logged by the caller).
func IsNextApp(dir string) bool {
	raw, err := os.ReadFile(filepath.Join(dir, "package.json"))
	if err != nil {
		return false
	}
	var pkg struct {
		Dependencies    map[string]string `json:"dependencies"`
		DevDependencies map[string]string `json:"devDependencies"`
	}
	if err := json.Unmarshal(raw, &pkg); err != nil {
		return false
	}
	_, inDeps := pkg.Dependencies["next"]
	_, inDev := pkg.DevDependencies["next"]
	return inDeps || inDev
}

// WriteImageBundle writes CRN's deterministic on-prem delivery bundle into dir,
// overwriting any model-produced versions:
//   - Dockerfile             (opaque app image — standalone, no source)
//   - .dockerignore
//   - Dockerfile.migrate     (DB schema+seed image — no app source)
//   - docker-compose.customer.yml (Postgres + migrate + app; customer runs this)
//   - INSTALL.md
// appImage/migrateImage are the (deterministic) tags the pipeline will build+push;
// registry + port are rendered into the compose/INSTALL. Returns false (no error)
// when dir is not a Next app — nothing to bundle.
func WriteImageBundle(dir, appImage, migrateImage, registry string, port int, logger *slog.Logger) (bool, error) {
	if logger == nil {
		logger = slog.Default()
	}
	if !IsNextApp(dir) {
		return false, nil
	}
	rep := strings.NewReplacer(
		"{{APP_IMAGE}}", appImage,
		"{{MIGRATE_IMAGE}}", migrateImage,
		"{{REGISTRY}}", registry,
		"{{PORT}}", strconv.Itoa(port),
	)
	for _, f := range []struct{ name, body string }{
		{"Dockerfile", productionDockerfile},
		{".dockerignore", dockerIgnore},
		{"Dockerfile.migrate", migrateDockerfile},
		{"docker-compose.customer.yml", rep.Replace(customerCompose)},
		{"INSTALL.md", rep.Replace(installMD)},
	} {
		if err := os.WriteFile(filepath.Join(dir, f.name), []byte(f.body), 0o644); err != nil {
			return false, fmt.Errorf("buildstep: write %s: %w", f.name, err)
		}
	}
	return true, nil
}

// imagePlatform is the target platform for demo images. Customers run on amd64
// (x86_64) machines while CRN often builds on arm64 Macs, so we pin it — Docker
// Desktop's buildx emulates the cross-build via QEMU. Not runtime-configurable
// yet; change here if an arm64 customer target ever appears.
const imagePlatform = "linux/amd64"

// BuildImage runs `docker build --platform linux/amd64 -f <dockerfile> -t <tag>
// <dir>`, streaming combined output to the logger. Requires a Docker daemon +
// buildx on the host.
func BuildImage(ctx context.Context, dir, dockerfile, tag string, logger *slog.Logger) error {
	// -f is resolved relative to the docker process's CWD, NOT the build context. CRN
	// runs from its own repo root (which has a Go server Dockerfile), so a bare
	// "Dockerfile" would match THAT instead of the workspace's — build the wrong
	// image. Always pass the context-absolute path.
	return runDocker(ctx, logger, "build", "--platform", imagePlatform, "-f", filepath.Join(dir, dockerfile), "-t", tag, dir)
}

// PushImage runs `docker push tag`. The host must already be `docker login`'d to
// the registry (CRN uses ambient docker credentials — like git uses ambient git
// credentials — rather than handling auth itself).
func PushImage(ctx context.Context, tag string, logger *slog.Logger) error {
	return runDocker(ctx, logger, "push", tag)
}

// SaveImages writes a `docker save` tarball of images to outPath — an air-gap
// bundle a customer can `docker load < images.tar`. Requires a Docker daemon.
func SaveImages(ctx context.Context, outPath string, images []string, logger *slog.Logger) error {
	return runDocker(ctx, logger, append([]string{"save", "-o", outPath}, images...)...)
}

// runDocker execs the host `docker` CLI, capturing combined output so a failure
// surfaces the real error (not just a non-zero exit). The returned error wraps a
// tail of docker's own output, so it propagates to build_events/the FTC DV callback
// — the operator sees the real reason (e.g. `npm ci` lockfile mismatch) instead of
// a bare "exit status 1". The full output is also logged at Error level.
func runDocker(ctx context.Context, logger *slog.Logger, args ...string) error {
	cmd := exec.CommandContext(ctx, "docker", args...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		trimmed := strings.TrimSpace(string(out))
		logger.Error("docker command failed", "args", strings.Join(args, " "), "output", trimmed)
		return fmt.Errorf("docker %s: %w\n%s", strings.Join(args, " "), err, tailLines(trimmed, 25))
	}
	logger.Info("docker command ok", "args", strings.Join(args, " "))
	return nil
}

// tailLines returns the last n lines of s (prefixed with an ellipsis when truncated)
// so a wrapped error carries the meaningful end of a build log without dumping the
// whole thing into build_events.
func tailLines(s string, n int) string {
	lines := strings.Split(s, "\n")
	if len(lines) <= n {
		return s
	}
	return "…\n" + strings.Join(lines[len(lines)-n:], "\n")
}
