package buildstep

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
)

// dockerbuild.go turns a built Next.js (App Router, standalone) demo into an
// opaque production Docker image and pushes it to a registry. Only the compiled
// standalone output ships in the image — no .tsx/source — so a customer can run
// the demo on their own LAN without seeing our code. CRN writes its own known-
// good Dockerfile (deterministic, mirrors the fitt-build harness asset) rather
// than trusting whatever the model produced, then execs the host `docker`.

// productionDockerfile is the multi-stage build for a Next.js app using
// output:"standalone". The runner stage copies ONLY .next/standalone + static +
// public, so source files never land in the image. Kept in sync with the
// fitt-build skill's assets/Dockerfile.
const productionDockerfile = `# Auto-written by FITT Code Runner — production image for this demo.
# Multi-stage: build the Next.js standalone app, then a lean runner that also
# self-migrates the schema on start (prisma db push) against an EXTERNAL Postgres
# (DATABASE_URL injected at run time). Only the compiled standalone output + the
# DB layer (schema/seed/prisma CLI) ship — no app source (.tsx).
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci --ignore-scripts

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# prisma generate needs no database; safe no-op if the project has no Prisma.
RUN npx prisma generate 2>/dev/null || true
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

# dbtools: prisma CLI + tsx (for seed) installed in isolation so migrate-on-start
# works WITHOUT shipping the full dev node_modules. Versions follow the app's
# package.json ranges. --ignore-scripts so a postinstall (prisma generate) doesn't
# run here (no schema present).
FROM node:20-alpine AS dbtools
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install --no-save --ignore-scripts --no-audit --no-fund prisma tsx

FROM node:20-alpine AS runner
WORKDIR /app
# openssl + libc6-compat: prisma's schema engine needs them at run time (db push).
RUN apk add --no-cache libc6-compat openssl
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs
# DB tooling first so the app's traced node_modules (standalone, copied next) wins
# for any shared dependency; prisma + tsx (absent from standalone) remain.
COPY --from=dbtools --chown=nextjs:nodejs /app/node_modules ./node_modules
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
# DB layer for migrate-on-start (no app source): schema + seed + the seed config in
# package.json. The skill guarantees a prisma/ dir on every build.
COPY --from=builder --chown=nextjs:nodejs /app/prisma ./prisma
COPY --from=builder --chown=nextjs:nodejs /app/package.json ./package.json
# Entrypoint: sync schema to the external DB then serve. db push runs WITHOUT the
# destructive-drop flag, so an additive change applies (data kept) while a destructive
# one FAILS LOUDLY (container won't start) instead of silently dropping data. Seed
# only when DEMO_SEED=1 (idempotent upsert). No-op migrate when the app has no Prisma.
RUN printf '#!/bin/sh\nset -e\nif [ -f prisma/schema.prisma ]; then\n  echo "[crn] migrate-on-start: prisma db push"\n  npx prisma db push --skip-generate\n  if [ "${DEMO_SEED:-0}" = "1" ]; then echo "[crn] seeding demo data"; npx prisma db seed || echo "[crn] seed failed (continuing)"; fi\nfi\nexec node server.js\n' > /app/docker-entrypoint.sh \
  && chmod +x /app/docker-entrypoint.sh \
  && chown nextjs:nodejs /app/docker-entrypoint.sh
USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
CMD ["/app/docker-entrypoint.sh"]
`

const dockerIgnore = `node_modules
.next
.git
.env
.env.*
Dockerfile
.dockerignore
npm-debug.log
`

// customerCompose runs the delivered demo against an EXTERNAL Postgres the operator
// supplies via DATABASE_URL — no bundled database, no separate migrate service. The
// app image self-migrates (prisma db push) on start. Placeholders rendered per build.
const customerCompose = `# Auto-generated by FITT Code Runner — run this demo against your OWN Postgres.
#   DATABASE_URL=postgresql://user:pass@host:5432/db docker compose -f docker-compose.customer.yml up -d
# No source ships (app is a compiled image). The app self-migrates its schema on start
# (prisma db push); set DEMO_SEED=1 to also load example data.
services:
  app:
    image: {{APP_IMAGE}}
    environment:
      DATABASE_URL: "${DATABASE_URL:?set DATABASE_URL to your Postgres, e.g. postgresql://user:pass@host:5432/db}"
      # DEMO_SEED: "1"   # uncomment to load example seed data on start
    ports:
      - "${APP_PORT:-{{PORT}}}:3000"
`

// DemoEnvExample is the runtime env contract for the delivered demo image — an
// example a consumer (FTC DV) can adapt. The operator supplies the real values at
// run time (compose/orchestrator); NONE of these are baked into the image. Mirrors
// what customerCompose injects, so keep the two in step.
type DemoEnvExample struct {
	// DatabaseURL is REQUIRED — the app self-migrates + reads it.
	DatabaseURL string `json:"DATABASE_URL"`
	// Port is the port the app listens on INSIDE the container (fixed).
	Port string `json:"PORT"`
	// AppPort is the suggested HOST port to publish → container 3000 (per-project,
	// avoids collisions); override freely.
	AppPort string `json:"APP_PORT"`
	// DevEmail/DevPassword are the fallback dev-login credentials. When the app has
	// authentication and DEMO_SEED=1, the seed upserts a login user from these so the
	// UAT is signable-in out of the box. The operator OVERRIDES them (ignored by apps
	// without auth). Never a real secret — change for anything beyond a demo.
	DevEmail    string `json:"DEV_EMAIL"`
	DevPassword string `json:"DEV_PASSWORD"`
}

// NewDemoEnvExample builds the env contract for a demo whose per-project host port
// is `port` (from ScaffoldPort).
func NewDemoEnvExample(port int) DemoEnvExample {
	return DemoEnvExample{
		DatabaseURL: "postgresql://USER:PASSWORD@HOST:5432/DB?schema=public",
		Port:        "3000",
		AppPort:     strconv.Itoa(port),
		DevEmail:    "dev@fitt.local",
		DevPassword: "changeme",
	}
}

const installMD = `# INSTALL — รัน demo นี้บนเครื่องคุณ

App เป็น image ที่ compile แล้ว (**ไม่มี source code**) และ **self-migrate**: ตอน start มัน
รัน ` + "`prisma db push`" + ` สร้าง/sync schema ใส่ **Postgres ของคุณเอง** (ต่อผ่าน ` + "`DATABASE_URL`" + `) แล้วค่อยเปิด demo.

## ต้องมี
- Docker (+ Compose ถ้าใช้ compose)
- **Postgres ของคุณเอง** + database ว่าง 1 อัน + connection string (` + "`DATABASE_URL`" + `)
- เข้าถึง image registry ได้ (หรือมีไฟล์ image tarball)

## รัน (docker run)
` + "```bash" + `
# ถ้า registry ต้อง login (deploy token):
docker login {{REGISTRY}} -u <user> -p <token>

docker run -d -p {{PORT}}:3000 \
  -e DATABASE_URL="postgresql://user:pass@host:5432/db" \
  {{APP_IMAGE}}
` + "```" + `
เปิด http://localhost:{{PORT}}

## รัน (compose)
` + "```bash" + `
DATABASE_URL="postgresql://user:pass@host:5432/db" \
  docker compose -f docker-compose.customer.yml up -d
` + "```" + `

## เกิดอะไรขึ้นตอน start
1. app รัน ` + "`prisma db push`" + ` → สร้าง/sync schema ใน DB ของคุณ (additive = data เดิมอยู่ครบ)
2. (ถ้า ` + "`DEMO_SEED=1`" + `) โหลด seed data ตัวอย่าง
3. เปิด demo ที่ port

## อัปเดตเป็นเวอร์ชันใหม่
เปลี่ยน tag ` + "`:v<n>`" + ` (docker run/compose) แล้วรันใหม่ ชี้ ` + "`DATABASE_URL`" + ` เดิม — additive change data อยู่ครบ

## ⚠️ ข้อควรรู้
- schema เปลี่ยนแบบ **destructive** (ลบ/rename column ที่มี data) → ` + "`db push`" + ` จะ **fail ไม่ start** (กัน data หาย) ไม่ drop เงียบ — ต้อง migrate มือ
- **backup DB ก่อนอัปเวอร์ชัน** ที่มี schema เปลี่ยนใหญ่
`

// DemoImageTag builds the image tag for a build:
// "<registry>/crn-demo-<slug>-<id8>:v<n>" (registry omitted when empty -> a
// local-only tag). The 8-char project-id suffix keeps two different projects
// that happen to share a demo name from colliding on the same image repo (both
// use per-project build numbers, so v1 would otherwise overwrite v1). name is
// sanitized to the docker repo charset.
func DemoImageTag(registry, name, projectID string, buildNo int) string {
	id8 := projectID
	if len(id8) > 8 {
		id8 = id8[:8]
	}
	repo := "crn-demo-" + dockerSlug(name)
	if id8 != "" {
		repo += "-" + id8
	}
	if registry != "" {
		repo = strings.TrimRight(registry, "/") + "/" + repo
	}
	return fmt.Sprintf("%s:v%d", repo, buildNo)
}

// dockerSlug lowercases name and keeps only the docker repo charset
// ([a-z0-9._-]), collapsing runs of other characters to a single "-". Falls back
// to "demo" if nothing usable remains.
func dockerSlug(name string) string {
	var b strings.Builder
	lastDash := false
	for _, r := range strings.ToLower(name) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
			lastDash = false
		default:
			if !lastDash && b.Len() > 0 {
				b.WriteByte('-')
				lastDash = true
			}
		}
	}
	s := strings.Trim(b.String(), "-")
	if s == "" {
		return "demo"
	}
	return s
}

// IsNextApp reports whether dir looks like a Next.js app (package.json depends on
// "next"). The docker-image pipeline only handles Next standalone builds; other
// stacks are skipped (logged by the caller).
func IsNextApp(dir string) bool {
	raw, err := os.ReadFile(filepath.Join(dir, "package.json"))
	if err != nil {
		return false
	}
	var pkg struct {
		Dependencies    map[string]string `json:"dependencies"`
		DevDependencies map[string]string `json:"devDependencies"`
	}
	if err := json.Unmarshal(raw, &pkg); err != nil {
		return false
	}
	_, inDeps := pkg.Dependencies["next"]
	_, inDev := pkg.DevDependencies["next"]
	return inDeps || inDev
}

// WriteImageBundle writes CRN's deterministic on-prem delivery bundle into dir,
// overwriting any model-produced versions:
//   - Dockerfile             (opaque, self-migrating app image — standalone, no source)
//   - .dockerignore
//   - docker-compose.customer.yml (app only; points at the operator's external Postgres)
//   - INSTALL.md
// appImage is the (deterministic) tag the pipeline will build+push; registry + port
// are rendered into the compose/INSTALL. The app image self-migrates on start, so
// there is no separate migrate image. Returns false (no error) when dir is not a
// Next app — nothing to bundle.
func WriteImageBundle(dir, appImage, registry string, port int, logger *slog.Logger) (bool, error) {
	if logger == nil {
		logger = slog.Default()
	}
	if !IsNextApp(dir) {
		return false, nil
	}
	rep := strings.NewReplacer(
		"{{APP_IMAGE}}", appImage,
		"{{REGISTRY}}", registry,
		"{{PORT}}", strconv.Itoa(port),
	)
	for _, f := range []struct{ name, body string }{
		{"Dockerfile", productionDockerfile},
		{".dockerignore", dockerIgnore},
		{"docker-compose.customer.yml", rep.Replace(customerCompose)},
		{"INSTALL.md", rep.Replace(installMD)},
	} {
		if err := os.WriteFile(filepath.Join(dir, f.name), []byte(f.body), 0o644); err != nil {
			return false, fmt.Errorf("buildstep: write %s: %w", f.name, err)
		}
	}
	return true, nil
}

// imagePlatform is the target platform for demo images. Customers run on amd64
// (x86_64) machines while CRN often builds on arm64 Macs, so we pin it — Docker
// Desktop's buildx emulates the cross-build via QEMU. Not runtime-configurable
// yet; change here if an arm64 customer target ever appears.
const imagePlatform = "linux/amd64"

// BuildImage runs `docker build --platform linux/amd64 -f <dockerfile> -t <tag>
// <dir>`, streaming combined output to the logger. Requires a Docker daemon +
// buildx on the host.
func BuildImage(ctx context.Context, dir, dockerfile, tag string, logger *slog.Logger) error {
	// -f is resolved relative to the docker process's CWD, NOT the build context. CRN
	// runs from its own repo root (which has a Go server Dockerfile), so a bare
	// "Dockerfile" would match THAT instead of the workspace's — build the wrong
	// image. Always pass the context-absolute path.
	return runDocker(ctx, logger, "build", "--platform", imagePlatform, "-f", filepath.Join(dir, dockerfile), "-t", tag, dir)
}

// PushImage runs `docker push tag`. The host must already be `docker login`'d to
// the registry (CRN uses ambient docker credentials — like git uses ambient git
// credentials — rather than handling auth itself).
func PushImage(ctx context.Context, tag string, logger *slog.Logger) error {
	return runDocker(ctx, logger, "push", tag)
}

// SaveImages writes a `docker save` tarball of images to outPath — an air-gap
// bundle a customer can `docker load < images.tar`. Requires a Docker daemon.
func SaveImages(ctx context.Context, outPath string, images []string, logger *slog.Logger) error {
	return runDocker(ctx, logger, append([]string{"save", "-o", outPath}, images...)...)
}

// runDocker execs the host `docker` CLI, capturing combined output so a failure
// surfaces the real error (not just a non-zero exit). The returned error wraps a
// tail of docker's own output, so it propagates to build_events/the FTC DV callback
// — the operator sees the real reason (e.g. `npm ci` lockfile mismatch) instead of
// a bare "exit status 1". The full output is also logged at Error level.
func runDocker(ctx context.Context, logger *slog.Logger, args ...string) error {
	cmd := exec.CommandContext(ctx, "docker", args...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		trimmed := strings.TrimSpace(string(out))
		logger.Error("docker command failed", "args", strings.Join(args, " "), "output", trimmed)
		return fmt.Errorf("docker %s: %w\n%s", strings.Join(args, " "), err, tailLines(trimmed, 25))
	}
	logger.Info("docker command ok", "args", strings.Join(args, " "))
	return nil
}

// tailLines returns the last n lines of s (prefixed with an ellipsis when truncated)
// so a wrapped error carries the meaningful end of a build log without dumping the
// whole thing into build_events.
func tailLines(s string, n int) string {
	lines := strings.Split(s, "\n")
	if len(lines) <= n {
		return s
	}
	return "…\n" + strings.Join(lines[len(lines)-n:], "\n")
}
