package buildstep

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
)

// scaffold.go makes a DB-backed (Prisma) demo runnable with ZERO manual setup.
// After generation, CRN drops a one-command docker-compose (Postgres + app,
// auto schema-push + seed) plus a QUICKSTART so a cloned repo "just runs" —
// `docker compose up` for Docker users, or the documented steps for manual runs.

// dockerComposeYML is a dev-oriented one-command runner: Postgres + the app
// (node:20, source-mounted) with an entrypoint that installs deps, pushes the
// Prisma schema, seeds, and starts the dev server. node:20 (not alpine) so the
// Prisma engine works without musl/openssl fiddling.
const dockerComposeYML = `# Auto-generated by FITT Code Runner — one-command local run for this demo.
# ` + "`docker compose up`" + ` starts Postgres, applies the Prisma schema, seeds the
# demo data, and serves the app. Default port 3000; if it is busy, pick another:
#   ` + "`APP_PORT=3005 docker compose up`" + `
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    image: node:20
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://app:app@db:5432/app?schema=public"
      APP_PORT: "${APP_PORT:-3000}"
    # Install, sync + seed the DB, print where to open it, then run the dev server.
    # $$APP_PORT survives compose interpolation and is expanded in the container.
    command:
      - sh
      - -c
      - |
        npm install &&
        npx prisma db push &&
        npx prisma db seed &&
        printf '\n▶ Demo ready — open http://localhost:%s\n\n' "$$APP_PORT" &&
        npm run dev -- -p 3000 -H 0.0.0.0
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

volumes:
  dbdata:
`

// NOTE: command blocks below contain ONLY bare commands — no trailing "# ..."
// comments — so pasting a whole block is safe even in shells where inline `#`
// is not a comment (e.g. zsh without interactive_comments). Explanations go in
// prose between the blocks.
const quickstartMD = `# QUICKSTART — run this demo locally

This app is **Next.js + Prisma + PostgreSQL**, so it needs a database.

## Option A — one command (Docker)
` + "```bash\ndocker compose up\n```" + `
Starts Postgres, applies the schema, seeds the demo data, and serves the app at
http://localhost:3000. Nothing else to set up. If port 3000 is busy, pick another:
` + "```bash\nAPP_PORT=3005 docker compose up\n```" + `

## Option B — manual (your own Postgres)
Copy the env template, then set ` + "`DATABASE_URL`" + ` in ` + "`.env`" + ` to your Postgres:
` + "```bash\ncp .env.example .env\n```" + `
Then install, create the schema, seed, and run:
` + "```bash\nnpm install\nnpx prisma db push\nnpx prisma db seed\nnpm run dev\n```" + `
The app serves at http://localhost:3000. If port 3000 is busy, run
` + "`npm run dev -- -p <port>`" + ` or change the ports mapping in docker-compose.yml.

See BUILD_NOTES.md for the full stack + database schema.
`

// ScaffoldRun writes the one-command runner (docker-compose.yml + QUICKSTART.md)
// into a DB-backed build so it runs with no manual DB setup. It is a no-op for
// apps without a Prisma schema (a static app needs no database). It OVERWRITES
// any generator-produced runner: model-generated Dockerfiles/composes have been
// unreliable (e.g. a deps-stage `prisma generate` before the schema is copied,
// or a compose referencing non-existent npm scripts), so CRN's deterministic,
// self-contained version wins — the same reasoning as the injected widget.
// Returns whether it wrote (so the caller can surface a "ready to run" note).
func ScaffoldRun(dir string, logger *slog.Logger) (bool, error) {
	if logger == nil {
		logger = slog.Default()
	}
	// Only DB-backed apps need this — detect a Prisma schema.
	if _, err := os.Stat(filepath.Join(dir, "prisma", "schema.prisma")); err != nil {
		return false, nil
	}

	for _, f := range []struct{ name, body string }{
		{"docker-compose.yml", dockerComposeYML},
		{"QUICKSTART.md", quickstartMD},
	} {
		if err := os.WriteFile(filepath.Join(dir, f.name), []byte(f.body), 0o644); err != nil {
			return false, fmt.Errorf("buildstep: write %s: %w", f.name, err)
		}
	}
	return true, nil
}
